### ISSUE TITLE
Error: Debug Failure.

### ISSUE THREAD

**Issue by Seanitzel** [ts-docs/ts-docs#4]
**Describe the bug**
Getting the error msg "Error: Debug Failure." when trying to generate the docs.

**To Reproduce**
Tried to run it on [this library](https://github.com/Seanitzel/note-art)

**Expected behavior**
Docs would be generated or a better error msg.

**Full error msg**
(node:47427) UnhandledPromiseRejectionWarning: Error: Debug Failure. Unexpected moduleResolution: node
    at Object.resolveModuleName (user/Note-Art/node_modules/typescript/lib/typescript.js:41605:37)
    at Object.defaultHost.resolveModuleNames (user/Note-Art/node_modules/@ts-docs/extractor/dist/extractor/Host.js:49:53)
    at actualResolveModuleNamesWorker (user/Note-Art/node_modules/typescript/lib/typescript.js:111711:133)
    at resolveModuleNamesWorker (user/Note-Art/node_modules/typescript/lib/typescript.js:111977:26)
    at resolveModuleNamesReusingOldState (user/Note-Art/node_modules/typescript/lib/typescript.js:112074:24)
    at processImportedModules (user/Note-Art/node_modules/typescript/lib/typescript.js:113532:35)
    at findSourceFileWorker (user/Note-Art/node_modules/typescript/lib/typescript.js:113333:17)
    at findSourceFile (user/Note-Art/node_modules/typescript/lib/typescript.js:113194:26)
    at user/Note-Art/node_modules/typescript/lib/typescript.js:113146:85
    at getSourceFileFromReferenceWorker (user/Note-Art/node_modules/typescript/lib/typescript.js:113113:34)

**Desktop:**
 - OS: MacOS Big sur

**Comment by GoogleFeud** [comment]
Thanks for reporting it! The issue comes from `ts-extractor`, the options weren't passed correctly. Everything should be working fine now, try it out by downloading the repository since the change hasn't been published to npm yet: 
```npm i ts-docs/ts-docs```

**Comment by GoogleFeud** [comment]
Issue is fixed in 0.1.2!

**Comment by insyri** [comment]
This seems like a separate bug, so yes, please open a new issue!

**Comment by Seanitzel** [comment]
Awesome!
Love my new docs 😄 

https://note-art-docs.netlify.app/
